### PR TITLE
CI: Update pipelines to Xcode 12.2, iOS 14.2 and iPhone 12

### PR DESCRIPTION
**Pull request by EwoutH**
Updates the build.yml Azure pipeline to use:
 - Xcode 12.2
 - iOS 14.2
 - iPhone 12 (as simulation target)

Using Xcode 12.2 improves support for the iPhone 12 series and devices on iOS 14.2.

Also updates the CI.yml Github Actions workflow to target iPhone 12.

### CODE REVIEW

**Comment by EwoutH** [comment]
This PR also fixes the GitHub Actions CI, which is currently failing.

Please squash when merging.

**Comment by roelspruit** [comment]
Hey. Thanks for this PR. We're currently preparing a new release and would rather not mess with pipelines during this process, especially because this change might also impact our tests (snapshot tests are very susceptible to breaking when switching to another version of iOS for testing. Therefore we will temporarily hold off on merging this PR. I expect we can merge it within 1 or 2 weeks.

**Comment by EwoutH** [comment]
@roelspruit Sounds good, marked it as draft right now. Please hit me up when you're ready!

**Comment by roelspruit** [comment]
Hi. We mirrored this PR to our internal repository and merged it in. This should have also marked this PR as "merged" but I guess it didn't because it was marked as draft. Anyway, your code made it in! Thank you very much for the work. It's so nice to see that little green checkmark on GitHub again ;) I'm going to close this PR now.

**Comment by EwoutH** [comment]
Thanks for merging!

**Pull request closed without merging**
