### PR TITLE
GitHub Actions Patch (continuous integration testing & reproducible builds)

### PR DESCRIPTION
**Pull request by jsoeterbroek**
This patch allows for GitHub Actions CI.

screenshot1

screenshot2

### CODE REVIEW

**Comment by jsoeterbroek** [comment]
@JolandaVerhoef @rvandijke Please review (and merge)

**Comment by dirkx** [comment]
Lovely !

**Comment by dirkx** [comment]
Moet je nog niet een pull hebben ?

**Comment by jsoeterbroek** [comment]
@rvandijke  @dirkx I have reorganised the code in the PR a bit (and squashed the many commits together) and will need a re-review. 

The prep and build phases now run succesfull, but the test phase now throws a (legitimate) error:

`xcodebuild clean test -project EN.xcodeproj -scheme ENCore`

--------------------------------------------------------------

```
** CLEAN SUCCEEDED **

note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description
warning: The Mac Catalyst deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 13.5, but the range of supported deployment target versions is 13.1 to 13.4.99. (in target 'ENCoreTests' from project 'EN')
warning: The Mac Catalyst deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 13.5, but the range of supported deployment target versions is 13.1 to 13.4.99. (in target 'ENCore' from project 'EN')
error: ExposureNotification is not available when building for Mac Catalyst. You may need to restrict the platforms for which this framework should be linked in the target editor. (in target 'ENCore' from project 'EN')


Testing failed:
	ExposureNotification is not available when building for Mac Catalyst. You may need to restrict the platforms for which this framework should be linked in the target editor.
Test session results, code coverage, and logs:
	Testing cancelled because the build failed.

** TEST FAILED **

	/Users/runner/Library/Developer/Xcode/DerivedData/EN-cmozisvvooofdweawrlcvpkzbvjl/Logs/Test/Run-ENCore-2020.07.18_12-58-07-+0000.xcresult

##[error]Process completed with exit code 65.
```

**Comment by dirkx** [comment]
Very nice !

**Comment by JolandaVerhoef** [comment]
Thank you so much for writing this using Github Actions!

**Comment by rvandijke** [comment]
Will have a look today!

**Comment by rvandijke** [comment]
In able to resolve the xcodebuild error (and to merge this successfully) Xcodegen needs to be patched:

https://github.com/yonaskolb/XcodeGen/issues/900

I've upvoted the issue and will have a look at putting up a PR myself for it, but at this moment I do have a few more important priorities. @jsoeterbroek do you think this is something you could take up by chance? A downside of relying on Xcodegen, but it already saved us a lot of time :)

**Comment by jsoeterbroek** [comment]
@rvandijke 

Building and testing now runs successfully all the way through for example target 'iphone 11'.

Tests are mostly successfull, but also some failures (see test log attached):

[5_citest-iphone11.txt](https://github.com/minvws/nl-covid19-notification-app-ios/files/4949865/5_citest-iphone11.txt)

**Comment by jsoeterbroek** [comment]
> In able to resolve the xcodebuild error (and to merge this successfully) Xcodegen needs to be patched:
> 
> [yonaskolb/XcodeGen#900](https://github.com/yonaskolb/XcodeGen/issues/900)
> 
> I've upvoted the issue and will have a look at putting up a PR myself for it, but at this moment I do have a few more important priorities. @jsoeterbroek do you think this is something you could take up by chance? A downside of relying on Xcodegen, but it already saved us a lot of time :)

**Comment by rvandijke** [comment]
Thanks for updating. Will patch it locally and review it right now

**Comment by rvandijke** [comment]
This has been landed (by rebasing)

**Pull request closed without merging**
