### PR TITLE
Patch for #23

### PR DESCRIPTION
**Pull request by jsoeterbroek**
Patch for #23

### CODE REVIEW

**Comment by sbarow** [comment]
Thanks for the PR @jsoeterbroek this is on our Radar. We will have a look at this on our internal repo.

**Comment by rvandijke** [comment]
@jsoeterbroek This is still required, correct? Even after PR 26?

**Comment by jsoeterbroek** [comment]
Yes.

**Comment by jsoeterbroek** [comment]
Both ipadiff and bindiff repositories **do not** have a license in place. So, this means that **both are not legal to be used in this repo** at the moment.

I have requested both projects to include a valid licence:

```
# bindiff
github repository: https://github.com/dadadel/bindiff

## requested license
https://github.com/dadadel/bindiff/issues/1

# ipadiff
github repository: https://github.com/TelegramMessenger/telegram-ios.git

## requested license
https://github.com/TelegramMessenger/Telegram-iOS/issues/337

```

**Comment by roelspruit** [comment]
I'm sorry this has been left open and without comment for such a long time. We have had quite some work to do over the last year and this issue never got enough priority over functional work, even though it would have been nice to have ticked this box. 

In the original discussion on https://github.com/minvws/nl-covid19-notification-app-coordination/issues/6 It was decided that the Escrow approach that was taken for release build validation was sufficient. Additionally, it seems the open source code that was used in this PR still does not have a clear license attached to it. That makes it impractical to continue with this approach.

For this reason, I'm going to close this PR. I do want to thank you for the work you put into this and once again I'm sorry we couldn't make better use of it.

**Pull request closed without merging**
