### PR TITLE
Improve English translation

### PR DESCRIPTION
**Pull request by edwardmp**
Thanks to everyone involved with creating this app!

I downloaded it today, and noticed that in the English translation there was something that may be a bit too literally translated from the Dutch equivalent, although I'm not a native English speaker either so correct me If I'm wrong :)

@sbarow I believe you seem to be working most on localisation, so tagging you.

### CODE REVIEW

**Comment by edwardmp** [comment]
Tests are failing because the snapshots are now outdated (cool way of testing, never used such a thing before). I'll check whether I can update the.

**Comment by sbarow** [comment]
Thanks @edwardmp I'll send this to our UX writer for confirmation. 

Regarding the snapshot tests you just need to re-record the snapshot tests. Go to the class which has failing snapshot tests and in the `setUp` method change the `record` value to `true`, run the tests and then change the value back to `false`.

**Comment by edwardmp** [comment]
@sbarow yep, see how I could do it but holiday WiFi too poor to download all deps ;)

**Comment by sbarow** [comment]
> @sbarow yep, see how I could do it but holiday WiFi too poor to download all deps ;)

Ah, I'll fix the snapshots and merge this.

**Comment by edwardmp** [comment]
@sbarow awesome! Already signed the CLA as you can see above.

**Comment by edwardmp** [comment]
@sbarow thanks! Any reason why the original history isn't kept?

**Pull request closed without merging**
